export let data = [
  {
    "id": 1,
    "name": "Jackass Presents: Bad Grandpa",
    "year": "2013",
    "genre": "Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTg4NjIwMTI5OV5BMl5BanBnXkFtZTgwNjU1MTMyMDE@._V1_SX300.jpg",
    "rated": "R",
    "released": "25 Oct 2013",
    "runtime": "92 min",
    "director": "Jeff Tremaine",
    "actors": "Johnny Knoxville, Jackson Nicoll, Gregorio",
    "language": "Spanish, English",
    "plot": "86-year-old Irving Zisman takes a trip from Nebraska to North Carolina to take his 8 year-old grandson, Billy, back to his real father.",
    "country": "United States",
    "imdbVotes": "95,344",
    "imdbRating": "6.5",
    "status": true,
    "createdAt": "2022-09-23T18:38:26.960Z",
    "updatedAt": "2022-09-23T18:38:26.960Z",
    "deletedAt": null
  },
  {
    "id": 2,
    "name": "The Adam Project",
    "year": "2022",
    "genre": "Action, Adventure, Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BOWM0YWMwMDQtMjE5NS00ZTIwLWE1NWEtODViMWZjMWI2OTU3XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "11 Mar 2022",
    "runtime": "106 min",
    "director": "Shawn Levy",
    "actors": "Ryan Reynolds, Walker Scobell, Mark Ruffalo",
    "language": "English",
    "plot": "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self for a mission to save the future.",
    "country": "United States",
    "imdbVotes": "192,285",
    "imdbRating": "6.7",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.161Z",
    "updatedAt": "2022-09-23T18:38:27.161Z",
    "deletedAt": null
  },
  {
    "id": 3,
    "name": "Spiderhead",
    "year": "2022",
    "genre": "Action, Crime, Drama",
    "poster": "https://m.media-amazon.com/images/M/MV5BNDVkZTc4OTktNTAyOC00MzQxLThiZjMtM2M3MTlmYzFjY2FkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "rated": "R",
    "released": "17 Jun 2022",
    "runtime": "106 min",
    "director": "Joseph Kosinski",
    "actors": "Chris Hemsworth, Miles Teller, Jurnee Smollett",
    "language": "English",
    "plot": "In the near future, convicts are offered the chance to volunteer as medical subjects to shorten their sentence. One such subject for a new drug capable of generating feelings of love begins questioning the reality of his emotions.",
    "country": "United States",
    "imdbVotes": "51,648",
    "imdbRating": "5.4",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.210Z",
    "updatedAt": "2022-09-23T18:38:27.210Z",
    "deletedAt": null
  },
  {
    "id": 4,
    "name": "Interstellar",
    "year": "2014",
    "genre": "Adventure, Drama, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "07 Nov 2014",
    "runtime": "169 min",
    "director": "Christopher Nolan",
    "actors": "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
    "language": "English",
    "plot": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    "country": "United States, United Kingdom, Canada",
    "imdbVotes": "1,774,128",
    "imdbRating": "8.6",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.213Z",
    "updatedAt": "2022-09-23T18:38:27.213Z",
    "deletedAt": null
  },
  {
    "id": 5,
    "name": "TRON: Legacy",
    "year": "2010",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTk4NTk4MTk1OF5BMl5BanBnXkFtZTcwNTE2MDIwNA@@._V1_SX300.jpg",
    "rated": "PG",
    "released": "17 Dec 2010",
    "runtime": "125 min",
    "director": "Joseph Kosinski",
    "actors": "Jeff Bridges, Garrett Hedlund, Olivia Wilde",
    "language": "English",
    "plot": "The son of a virtual world designer goes looking for his father and ends up inside the digital world that his father designed. He meets his father's corrupted creation and a unique ally who was born inside the digital world.",
    "country": "United States",
    "imdbVotes": "335,377",
    "imdbRating": "6.8",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.260Z",
    "updatedAt": "2022-09-23T18:38:27.260Z",
    "deletedAt": null
  },
  {
    "id": 6,
    "name": "The Lord of the Rings: The Fellowship of the Ring",
    "year": "2001",
    "genre": "Action, Adventure, Drama",
    "poster": "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "19 Dec 2001",
    "runtime": "178 min",
    "director": "Peter Jackson",
    "actors": "Elijah Wood, Ian McKellen, Orlando Bloom",
    "language": "English, Sindarin",
    "plot": "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    "country": "New Zealand, United States",
    "imdbVotes": "1,827,055",
    "imdbRating": "8.8",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.264Z",
    "updatedAt": "2022-09-23T18:38:27.264Z",
    "deletedAt": null
  },
  {
    "id": 7,
    "name": "Windfall",
    "year": "2022",
    "genre": "Crime, Drama, Thriller",
    "poster": "https://m.media-amazon.com/images/M/MV5BZjlhNzM4NjItMWRkNi00MWRmLWIzZmEtMmVlNGMwNzU3MmUzXkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_SX300.jpg",
    "rated": "R",
    "released": "18 Mar 2022",
    "runtime": "92 min",
    "director": "Charlie McDowell",
    "actors": "Jason Segel, Lily Collins, Jesse Plemons",
    "language": "English",
    "plot": "A man breaks into a tech billionaire's empty vacation home, but things go sideways when the arrogant mogul and his wife arrive for a last-minute getaway.",
    "country": "United States",
    "imdbVotes": "22,596",
    "imdbRating": "5.7",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.360Z",
    "updatedAt": "2022-09-23T18:38:27.360Z",
    "deletedAt": null
  },
  {
    "id": 8,
    "name": "The Matrix",
    "year": "1999",
    "genre": "Action, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    "rated": "R",
    "released": "31 Mar 1999",
    "runtime": "136 min",
    "director": "Lana Wachowski, Lilly Wachowski",
    "actors": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
    "language": "English",
    "plot": "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    "country": "United States, Australia",
    "imdbVotes": "1,889,334",
    "imdbRating": "8.7",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.363Z",
    "updatedAt": "2022-09-23T18:38:27.363Z",
    "deletedAt": null
  },
  {
    "id": 9,
    "name": "The Matrix Reloaded",
    "year": "2003",
    "genre": "Action, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BODE0MzZhZTgtYzkwYi00YmI5LThlZWYtOWRmNWE5ODk0NzMxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    "rated": "R",
    "released": "15 May 2003",
    "runtime": "138 min",
    "director": "Lana Wachowski, Lilly Wachowski",
    "actors": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
    "language": "English, French",
    "plot": "Freedom fighters Neo, Trinity and Morpheus continue to lead the revolt against the Machine Army, unleashing their arsenal of extraordinary skills and weaponry against the systematic forces of repression and exploitation.",
    "country": "United States",
    "imdbVotes": "590,057",
    "imdbRating": "7.2",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.460Z",
    "updatedAt": "2022-09-23T18:38:27.460Z",
    "deletedAt": null
  },
  {
    "id": 10,
    "name": "Silverton Siege",
    "year": "2022",
    "genre": "Action, Crime, Drama",
    "poster": "https://m.media-amazon.com/images/M/MV5BNGI4ZWU1MWUtNWYzNS00OTFlLWJhYjItNjFhMGZkMWJlMzJjXkEyXkFqcGdeQXVyODcxODU0OTM@._V1_SX300.jpg",
    "rated": "TV-MA",
    "released": "27 Apr 2022",
    "runtime": "2 min",
    "director": "Mandla Dube",
    "actors": "Thabo Rametsi, Arnold Vosloo, Noxolo Dlamini",
    "language": "English",
    "plot": "Follows three young freedom fighters who seek refuge in a South African bank in Silverton, and take the bank and its customers hostage and would only release them in exchange for the release of Nelson Mandela.",
    "country": "South Africa",
    "imdbVotes": "3,640",
    "imdbRating": "6.2",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.463Z",
    "updatedAt": "2022-09-23T18:38:27.463Z",
    "deletedAt": null
  },
  {
    "id": 11,
    "name": "Titanic",
    "year": "1997",
    "genre": "Drama, Romance",
    "poster": "https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "19 Dec 1997",
    "runtime": "194 min",
    "director": "James Cameron",
    "actors": "Leonardo DiCaprio, Kate Winslet, Billy Zane",
    "language": "English, Swedish, Italian, French",
    "plot": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
    "country": "United States",
    "imdbVotes": "1,154,441",
    "imdbRating": "7.9",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.465Z",
    "updatedAt": "2022-09-23T18:38:27.465Z",
    "deletedAt": null
  },
  {
    "id": 12,
    "name": "Toy Story",
    "year": "1995",
    "genre": "Animation, Adventure, Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_SX300.jpg",
    "rated": "G",
    "released": "22 Nov 1995",
    "runtime": "81 min",
    "director": "John Lasseter",
    "actors": "Tom Hanks, Tim Allen, Don Rickles",
    "language": "English",
    "plot": "A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy's bedroom.",
    "country": "United States",
    "imdbVotes": "980,431",
    "imdbRating": "8.3",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.365Z",
    "updatedAt": "2022-09-23T18:38:27.365Z",
    "deletedAt": null
  },
  {
    "id": 13,
    "name": "Tarzan",
    "year": "1999",
    "genre": "Animation, Adventure, Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BY2ZiYWUxN2ItYmQxZi00NDlkLWE2NDAtOTNmYTg1MDI0NDk1XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg",
    "rated": "G",
    "released": "18 Jun 1999",
    "runtime": "88 min",
    "director": "Chris Buck, Kevin Lima",
    "actors": "Tony Goldwyn, Minnie Driver, Brian Blessed",
    "language": "English",
    "plot": "A man raised by gorillas must decide where he really belongs when he discovers he is a human.",
    "country": "United States",
    "imdbVotes": "224,613",
    "imdbRating": "7.3",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.468Z",
    "updatedAt": "2022-09-23T18:38:27.468Z",
    "deletedAt": null
  },
  {
    "id": 14,
    "name": "Hot Seat",
    "year": "2022",
    "genre": "Thriller",
    "poster": "https://m.media-amazon.com/images/M/MV5BMWVmOTAyMmMtY2U3Yi00MmE3LWE4ZjItMzZmZDc1ZDUwMzJlXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg",
    "rated": "R",
    "released": "07 Jul 2022",
    "runtime": "99 min",
    "director": "James Cullen Bressack",
    "actors": "Mel Gibson, Kevin Dillon, Shannen Doherty",
    "language": "English",
    "plot": "An ex-hacker is forced to break into high-level banking institutions, another man must try to penetrate the booby trapped building to get the young man off the hot seat.",
    "country": "United States",
    "imdbVotes": "1,900",
    "imdbRating": "4.5",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.556Z",
    "updatedAt": "2022-09-23T18:38:27.556Z",
    "deletedAt": null
  },
  {
    "id": 15,
    "name": "Rambo",
    "year": "2008",
    "genre": "Action, Adventure, Thriller",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTI5Mjg1MzM4NF5BMl5BanBnXkFtZTcwNTAyNzUzMw@@._V1_SX300.jpg",
    "rated": "R",
    "released": "25 Jan 2008",
    "runtime": "92 min",
    "director": "Sylvester Stallone",
    "actors": "Sylvester Stallone, Julie Benz, Matthew Marsden",
    "language": "English, Burmese, Thai",
    "plot": "In Thailand, John Rambo joins a group of mercenaries to venture into war-torn Burma, and rescue a group of Christian aid workers who were kidnapped by the ruthless local infantry unit.",
    "country": "Germany, United States",
    "imdbVotes": "231,146",
    "imdbRating": "7.0",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.561Z",
    "updatedAt": "2022-09-23T18:38:27.561Z",
    "deletedAt": null
  },
  {
    "id": 16,
    "name": "Yaksha: Ruthless Operations",
    "year": "2022",
    "genre": "Action, Crime, Thriller",
    "poster": "https://m.media-amazon.com/images/M/MV5BZjFmMzYzMjgtNmJiNS00MTQ5LTljNzItZTg4MGM2ODE5YWIzXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg",
    "rated": "TV-14",
    "released": "08 Apr 2022",
    "runtime": "125 min",
    "director": "Hyeon Na",
    "actors": "Sol Kyung-gu, Park Hae-soo, Hiroyuki Ikeuchi",
    "language": "Korean, Chinese, Japanese, English",
    "plot": "Nicknamed after a human-devouring spirit, the ruthless leader of an overseas black ops team takes up a dangerous mission in a city riddled with spies.",
    "country": "South Korea",
    "imdbVotes": "3,353",
    "imdbRating": "6.2",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.563Z",
    "updatedAt": "2022-09-23T18:38:27.563Z",
    "deletedAt": null
  },
  {
    "id": 21,
    "name": "Top Gun",
    "year": "1986",
    "genre": "Action, Drama",
    "poster": "https://m.media-amazon.com/images/M/MV5BZjQxYTA3ODItNzgxMy00N2Y2LWJlZGMtMTRlM2JkZjI1ZDhhXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
    "rated": "PG",
    "released": "16 May 1986",
    "runtime": "110 min",
    "director": "Tony Scott",
    "actors": "Tom Cruise, Tim Robbins, Kelly McGillis",
    "language": "English",
    "plot": "As students at the United States Navy's elite fighter weapons school compete to be best in the class, one daring young pilot learns a few things from a civilian instructor that are not taught in the classroom.",
    "country": "United States",
    "imdbVotes": "414,099",
    "imdbRating": "6.9",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.756Z",
    "updatedAt": "2022-09-23T18:38:27.756Z",
    "deletedAt": null
  },
  {
    "id": 23,
    "name": "Harry Potter and the Prisoner of Azkaban",
    "year": "2004",
    "genre": "Adventure, Family, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTY4NTIwODg0N15BMl5BanBnXkFtZTcwOTc0MjEzMw@@._V1_SX300.jpg",
    "rated": "PG",
    "released": "04 Jun 2004",
    "runtime": "142 min",
    "director": "Alfonso Cuarón",
    "actors": "Daniel Radcliffe, Emma Watson, Rupert Grint",
    "language": "English, Latin, Old English",
    "plot": "Harry Potter, Ron and Hermione return to Hogwarts School of Witchcraft and Wizardry for their third year of study, where they delve into the mystery surrounding an escaped prisoner who poses a dangerous threat to the young wizard.",
    "country": "United Kingdom, United States",
    "imdbVotes": "623,933",
    "imdbRating": "7.9",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.767Z",
    "updatedAt": "2022-09-23T18:38:27.767Z",
    "deletedAt": null
  },
  {
    "id": 28,
    "name": "The Batman",
    "year": "2022",
    "genre": "Action, Crime, Drama",
    "poster": "https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "04 Mar 2022",
    "runtime": "176 min",
    "director": "Matt Reeves",
    "actors": "Robert Pattinson, Zoë Kravitz, Jeffrey Wright",
    "language": "English, Spanish, Latin, Italian",
    "plot": "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    "country": "United States",
    "imdbVotes": "592,633",
    "imdbRating": "7.9",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.864Z",
    "updatedAt": "2022-09-23T18:38:27.864Z",
    "deletedAt": null
  },
  {
    "id": 31,
    "name": "The Shawshank Redemption",
    "year": "1994",
    "genre": "Drama",
    "poster": "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "rated": "R",
    "released": "14 Oct 1994",
    "runtime": "142 min",
    "director": "Frank Darabont",
    "actors": "Tim Robbins, Morgan Freeman, Bob Gunton",
    "language": "English",
    "plot": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    "country": "United States",
    "imdbVotes": "2,640,847",
    "imdbRating": "9.3",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.963Z",
    "updatedAt": "2022-09-23T18:38:27.963Z",
    "deletedAt": null
  },
  {
    "id": 34,
    "name": "Doctor Strange",
    "year": "2016",
    "genre": "Action, Adventure, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "04 Nov 2016",
    "runtime": "115 min",
    "director": "Scott Derrickson",
    "actors": "Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams",
    "language": "English",
    "plot": "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",
    "country": "United States",
    "imdbVotes": "728,868",
    "imdbRating": "7.5",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.166Z",
    "updatedAt": "2022-09-23T18:38:28.166Z",
    "deletedAt": null
  },
  {
    "id": 35,
    "name": "2012",
    "year": "2009",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTY0MjEyODQzMF5BMl5BanBnXkFtZTcwMTczMjQ4Mg@@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "13 Nov 2009",
    "runtime": "158 min",
    "director": "Roland Emmerich",
    "actors": "John Cusack, Thandiwe Newton, Chiwetel Ejiofor",
    "language": "English, French, Tibetan, Mandarin, Russian, Hindi, Portuguese, Latin, Italian, Spanish",
    "plot": "A frustrated writer struggles to keep his family alive when a series of global catastrophes threatens to annihilate mankind.",
    "country": "United States",
    "imdbVotes": "375,933",
    "imdbRating": "5.8",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.225Z",
    "updatedAt": "2022-09-23T18:38:28.225Z",
    "deletedAt": null
  },
  {
    "id": 40,
    "name": "Minions",
    "year": "2015",
    "genre": "Animation, Adventure, Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTg2MTMyMzU0M15BMl5BanBnXkFtZTgwOTU3ODk4NTE@._V1_SX300.jpg",
    "rated": "PG",
    "released": "10 Jul 2015",
    "runtime": "91 min",
    "director": "Kyle Balda, Pierre Coffin",
    "actors": "Sandra Bullock, Jon Hamm, Michael Keaton",
    "language": "English, Spanish",
    "plot": "Minions Stuart, Kevin, and Bob are recruited by Scarlet Overkill, a supervillain who, alongside her inventor husband Herb, hatches a plot to take over the world.",
    "country": "United States, United Kingdom",
    "imdbVotes": "237,077",
    "imdbRating": "6.4",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.262Z",
    "updatedAt": "2022-09-23T18:38:28.262Z",
    "deletedAt": null
  },
  {
    "id": 43,
    "name": "Fantastic Beasts and Where to Find Them",
    "year": "2016",
    "genre": "Adventure, Family, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjMxOTM1OTI4MV5BMl5BanBnXkFtZTgwODE5OTYxMDI@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "18 Nov 2016",
    "runtime": "132 min",
    "director": "David Yates",
    "actors": "Eddie Redmayne, Katherine Waterston, Alison Sudol",
    "language": "English, Central Khmer",
    "plot": "The adventures of writer Newt Scamander in New York's secret community of witches and wizards seventy years before Harry Potter reads his book in school.",
    "country": "United Kingdom, United States",
    "imdbVotes": "470,630",
    "imdbRating": "7.2",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.271Z",
    "updatedAt": "2022-09-23T18:38:28.271Z",
    "deletedAt": null
  },
  {
    "id": 45,
    "name": "The Godfather",
    "year": "1972",
    "genre": "Crime, Drama",
    "poster": "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    "rated": "R",
    "released": "24 Mar 1972",
    "runtime": "175 min",
    "director": "Francis Ford Coppola",
    "actors": "Marlon Brando, Al Pacino, James Caan",
    "language": "English, Italian, Latin",
    "plot": "The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.",
    "country": "United States",
    "imdbVotes": "1,823,905",
    "imdbRating": "9.2",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.276Z",
    "updatedAt": "2022-09-23T18:38:28.276Z",
    "deletedAt": null
  },
  {
    "id": 52,
    "name": "Spider-Man 3",
    "year": "2007",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BYTk3MDljOWQtNGI2My00OTEzLTlhYjQtOTQ4ODM2MzUwY2IwXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "04 May 2007",
    "runtime": "139 min",
    "director": "Sam Raimi",
    "actors": "Tobey Maguire, Kirsten Dunst, Topher Grace",
    "language": "English, French",
    "plot": "A strange black entity from another world bonds with Peter Parker and causes inner turmoil as he contends with new villains, temptations, and revenge.",
    "country": "United States",
    "imdbVotes": "583,395",
    "imdbRating": "6.2",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.637Z",
    "updatedAt": "2022-09-23T18:38:28.637Z",
    "deletedAt": null
  },
  {
    "id": 60,
    "name": "Black Rain",
    "year": "1989",
    "genre": "Action, Crime, Thriller",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjk1N2ZjOWYtN2FiMi00YzE4LTg1ZTctOGVmMjBlNzllNmUzXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    "rated": "R",
    "released": "22 Sep 1989",
    "runtime": "125 min",
    "director": "Ridley Scott",
    "actors": "Michael Douglas, Andy Garcia, Ken Takakura",
    "language": "English, Japanese",
    "plot": "Two NYC cops arrest a Yakuza member and must escort him when he's extradited to Japan.",
    "country": "United States",
    "imdbVotes": "55,119",
    "imdbRating": "6.6",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.818Z",
    "updatedAt": "2022-09-23T18:38:28.818Z",
    "deletedAt": null
  },
  {
    "id": 63,
    "name": "Jurassic Park",
    "year": "1993",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "11 Jun 1993",
    "runtime": "127 min",
    "director": "Steven Spielberg",
    "actors": "Sam Neill, Laura Dern, Jeff Goldblum",
    "language": "English, Spanish",
    "plot": "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
    "country": "United States",
    "imdbVotes": "975,123",
    "imdbRating": "8.2",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.966Z",
    "updatedAt": "2022-09-23T18:38:28.966Z",
    "deletedAt": null
  },
  {
    "id": 68,
    "name": "Spider-Man: No Way Home",
    "year": "2021",
    "genre": "Action, Adventure, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "17 Dec 2021",
    "runtime": "148 min",
    "director": "Jon Watts",
    "actors": "Tom Holland, Zendaya, Benedict Cumberbatch",
    "language": "English",
    "plot": "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    "country": "United States",
    "imdbVotes": "712,692",
    "imdbRating": "8.3",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.976Z",
    "updatedAt": "2022-09-23T18:38:28.976Z",
    "deletedAt": null
  },
  {
    "id": 71,
    "name": "Frozen",
    "year": "2013",
    "genre": "Animation, Adventure, Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTQ1MjQwMTE5OF5BMl5BanBnXkFtZTgwNjk3MTcyMDE@._V1_SX300.jpg",
    "rated": "PG",
    "released": "27 Nov 2013",
    "runtime": "102 min",
    "director": "Chris Buck, Jennifer Lee",
    "actors": "Kristen Bell, Idina Menzel, Jonathan Groff",
    "language": "English, Norwegian",
    "plot": "When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather co...",
    "country": "United States",
    "imdbVotes": "618,349",
    "imdbRating": "7.4",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.174Z",
    "updatedAt": "2022-09-23T18:38:29.174Z",
    "deletedAt": null
  },
  {
    "id": 17,
    "name": "Gangubai Kathiawadi",
    "year": "2022",
    "genre": "Biography, Crime, Drama",
    "poster": "https://m.media-amazon.com/images/M/MV5BN2M4NDM2NDItMzgzNy00OWRiLThhNjEtZDA2OWMyNTcwYzRjXkEyXkFqcGdeQXVyMTI1NDEyNTM5._V1_SX300.jpg",
    "rated": "TV-MA",
    "released": "25 Feb 2022",
    "runtime": "3 min",
    "director": "Sanjay Leela Bhansali",
    "actors": "Alia Bhatt, Shantanu Maheshwari, Vijay Raaz",
    "language": "Hindi, Telugu",
    "plot": "Duped and sold to a brothel, a young woman fearlessly reclaims her power, using underworld connections to preside over the world she was once a pawn in.",
    "country": "India",
    "imdbVotes": "53,306",
    "imdbRating": "7.0",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.657Z",
    "updatedAt": "2022-09-23T18:38:27.657Z",
    "deletedAt": null
  },
  {
    "id": 25,
    "name": "Morbius",
    "year": "2022",
    "genre": "Action, Adventure, Horror",
    "poster": "https://m.media-amazon.com/images/M/MV5BNTA3N2Q0ZTAtODJjNy00MmQzLWJlMmItOGFmNDI0ODgxN2QwXkEyXkFqcGdeQXVyMTM0NTUzNDIy._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "01 Apr 2022",
    "runtime": "104 min",
    "director": "Daniel Espinosa",
    "actors": "Jared Leto, Matt Smith, Adria Arjona",
    "language": "English, Spanish, Russian",
    "plot": "Biochemist Michael Morbius tries to cure himself of a rare blood disease, but he inadvertently infects himself with a form of vampirism instead.",
    "country": "United States",
    "imdbVotes": "107,478",
    "imdbRating": "5.2",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.859Z",
    "updatedAt": "2022-09-23T18:38:27.859Z",
    "deletedAt": null
  },
  {
    "id": 30,
    "name": "Heropanti 2",
    "year": "2022",
    "genre": "Action, Romance",
    "poster": "https://m.media-amazon.com/images/M/MV5BNTQxNjA3ZmEtZDE4Zi00OTA1LWFlZmUtZTFlYjk2YWQzNzI5XkEyXkFqcGdeQXVyNDAzNDk0MTQ@._V1_SX300.jpg",
    "rated": "N/A",
    "released": "29 Apr 2022",
    "runtime": "145 min",
    "director": "Ahmed Khan",
    "actors": "Tiger Shroff, Nawazuddin Siddiqui, Tara Sutaria",
    "language": "Hindi",
    "plot": "Babloo Ranawat, a genius hacker, is tasked with tracking down Laila, the mastermind behind the world's largest cyber-crime yet to occur. Will Babloo be able to stop him?",
    "country": "India",
    "imdbVotes": "26,071",
    "imdbRating": "2.6",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.868Z",
    "updatedAt": "2022-09-23T18:38:27.868Z",
    "deletedAt": null
  },
  {
    "id": 32,
    "name": "Beauty and the Beast",
    "year": "1991",
    "genre": "Animation, Family, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMzE5MDM1NDktY2I0OC00YWI5LTk2NzUtYjczNDczOWQxYjM0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    "rated": "G",
    "released": "22 Nov 1991",
    "runtime": "84 min",
    "director": "Gary Trousdale, Kirk Wise",
    "actors": "Paige O'Hara, Robby Benson, Jesse Corti",
    "language": "English, French",
    "plot": "A prince cursed to spend his days as a hideous monster sets out to regain his humanity by earning a young woman's love.",
    "country": "United States",
    "imdbVotes": "450,983",
    "imdbRating": "8.0",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.059Z",
    "updatedAt": "2022-09-23T18:38:28.059Z",
    "deletedAt": null
  },
  {
    "id": 37,
    "name": "Independence Day",
    "year": "1996",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BMGQwNDNkMmItYWY1Yy00YTZmLWE5OTAtODU0MGZmMzQ1NDdkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "03 Jul 1996",
    "runtime": "145 min",
    "director": "Roland Emmerich",
    "actors": "Will Smith, Bill Pullman, Jeff Goldblum",
    "language": "English",
    "plot": "The aliens are coming and their goal is to invade and destroy Earth. Fighting superior technology, mankind's best weapon is the will to survive.",
    "country": "United States",
    "imdbVotes": "572,893",
    "imdbRating": "7.0",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.168Z",
    "updatedAt": "2022-09-23T18:38:28.168Z",
    "deletedAt": null
  },
  {
    "id": 41,
    "name": "Uncharted",
    "year": "2022",
    "genre": "Action, Adventure",
    "poster": "https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "18 Feb 2022",
    "runtime": "116 min",
    "director": "Ruben Fleischer",
    "actors": "Tom Holland, Mark Wahlberg, Antonio Banderas",
    "language": "English, Spanish",
    "plot": "Street-smart Nathan Drake is recruited by seasoned treasure hunter Victor \"Sully\" Sullivan to recover a fortune amassed by Ferdinand Magellan, and lost 500 years ago by the House of Moncada.",
    "country": "Spain, United States",
    "imdbVotes": "183,692",
    "imdbRating": "6.3",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.265Z",
    "updatedAt": "2022-09-23T18:38:28.265Z",
    "deletedAt": null
  },
  {
    "id": 44,
    "name": "Spider-Man",
    "year": "2002",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BZDEyN2NhMjgtMjdhNi00MmNlLWE5YTgtZGE4MzNjMTRlMGEwXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "03 May 2002",
    "runtime": "121 min",
    "director": "Sam Raimi",
    "actors": "Tobey Maguire, Kirsten Dunst, Willem Dafoe",
    "language": "English",
    "plot": "When bitten by a genetically modified spider, a nerdy, shy, and awkward high school student gains spider-like abilities that he eventually must use to fight evil as a superhero after tragedy befalls his family.",
    "country": "United States",
    "imdbVotes": "807,242",
    "imdbRating": "7.4",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.273Z",
    "updatedAt": "2022-09-23T18:38:28.273Z",
    "deletedAt": null
  },
  {
    "id": 49,
    "name": "Wonder Woman",
    "year": "2017",
    "genre": "Action, Adventure, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTYzODQzYjQtNTczNC00MzZhLTg1ZWYtZDUxYmQ3ZTY4NzA1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "02 Jun 2017",
    "runtime": "141 min",
    "director": "Patty Jenkins",
    "actors": "Gal Gadot, Chris Pine, Robin Wright",
    "language": "English, German, Dutch, Flemish, French, Spanish, Chinese, Greek, Ancient (to 1453), North American Indian",
    "plot": "When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war, discovering her full powers and true destiny.",
    "country": "United States, China",
    "imdbVotes": "648,467",
    "imdbRating": "7.4",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.360Z",
    "updatedAt": "2022-09-23T18:38:28.360Z",
    "deletedAt": null
  },
  {
    "id": 51,
    "name": "Bait",
    "year": "2012",
    "genre": "Action, Fantasy, Horror",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTYzNjU4NTc5MV5BMl5BanBnXkFtZTcwNDE0NzAzOA@@._V1_SX300.jpg",
    "rated": "R",
    "released": "20 Sep 2012",
    "runtime": "2 min",
    "director": "Kimble Rendall",
    "actors": "Xavier Samuel, Sharni Vinson, Adrian Pang",
    "language": "English",
    "plot": "A freak tsunami traps shoppers at a coastal Australian supermarket inside the building - along with 12-foot Great White Sharks.",
    "country": "Australia, Singapore, China",
    "imdbVotes": "17,962",
    "imdbRating": "5.2",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.621Z",
    "updatedAt": "2022-09-23T18:38:28.621Z",
    "deletedAt": null
  },
  {
    "id": 54,
    "name": "Harry Potter and the Goblet of Fire",
    "year": "2005",
    "genre": "Adventure, Family, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTI1NDMyMjExOF5BMl5BanBnXkFtZTcwOTc4MjQzMQ@@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "18 Nov 2005",
    "runtime": "157 min",
    "director": "Mike Newell",
    "actors": "Daniel Radcliffe, Emma Watson, Rupert Grint",
    "language": "English, French, Latin",
    "plot": "Harry Potter finds himself competing in a hazardous tournament between rival schools of magic, but he is distracted by recurring nightmares.",
    "country": "United Kingdom, United States",
    "imdbVotes": "616,924",
    "imdbRating": "7.7",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.677Z",
    "updatedAt": "2022-09-23T18:38:28.677Z",
    "deletedAt": null
  },
  {
    "id": 59,
    "name": "Finding Dory",
    "year": "2016",
    "genre": "Animation, Adventure, Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BNzg4MjM2NDQ4MV5BMl5BanBnXkFtZTgwMzk3MTgyODE@._V1_SX300.jpg",
    "rated": "PG",
    "released": "17 Jun 2016",
    "runtime": "97 min",
    "director": "Andrew Stanton, Angus MacLane",
    "actors": "Ellen DeGeneres, Albert Brooks, Ed O'Neill",
    "language": "English, Indonesian",
    "plot": "Friendly but forgetful blue tang Dory begins a search for her long-lost parents, and everyone learns a few things about the real meaning of family along the way.",
    "country": "United States",
    "imdbVotes": "273,088",
    "imdbRating": "7.3",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.820Z",
    "updatedAt": "2022-09-23T18:38:28.820Z",
    "deletedAt": null
  },
  {
    "id": 64,
    "name": "Harry Potter and the Deathly Hallows: Part 1",
    "year": "2010",
    "genre": "Adventure, Family, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTQ2OTE1Mjk0N15BMl5BanBnXkFtZTcwODE3MDAwNA@@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "19 Nov 2010",
    "runtime": "146 min",
    "director": "David Yates",
    "actors": "Daniel Radcliffe, Emma Watson, Rupert Grint",
    "language": "English, Latin",
    "plot": "As Harry, Ron and Hermione race against time and evil to destroy the Horcruxes, they uncover the existence of the three most powerful objects in the wizarding world: the Deathly Hallows.",
    "country": "United Kingdom, United States",
    "imdbVotes": "540,164",
    "imdbRating": "7.7",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.970Z",
    "updatedAt": "2022-09-23T18:38:28.970Z",
    "deletedAt": null
  },
  {
    "id": 69,
    "name": "Frozen II",
    "year": "2019",
    "genre": "Animation, Adventure, Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjA0YjYyZGMtN2U0Ni00YmY4LWJkZTItYTMyMjY3NGYyMTJkXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_SX300.jpg",
    "rated": "PG",
    "released": "22 Nov 2019",
    "runtime": "103 min",
    "director": "Chris Buck, Jennifer Lee",
    "actors": "Kristen Bell, Idina Menzel, Josh Gad",
    "language": "English",
    "plot": "Anna, Elsa, Kristoff, Olaf and Sven leave Arendelle to travel to an ancient, autumn-bound forest of an enchanted land. They set out to find the origin of Elsa's powers in order to save their kingdom.",
    "country": "United States",
    "imdbVotes": "169,240",
    "imdbRating": "6.8",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.168Z",
    "updatedAt": "2022-09-23T18:38:29.168Z",
    "deletedAt": null
  },
  {
    "id": 74,
    "name": "Aquaman",
    "year": "2018",
    "genre": "Action, Adventure, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BOTk5ODg0OTU5M15BMl5BanBnXkFtZTgwMDQ3MDY3NjM@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "21 Dec 2018",
    "runtime": "143 min",
    "director": "James Wan",
    "actors": "Jason Momoa, Amber Heard, Willem Dafoe",
    "language": "English, Russian, Maori, Italian",
    "plot": "Arthur Curry, the human-born heir to the underwater kingdom of Atlantis, goes on a quest to prevent a war between the worlds of ocean and land.",
    "country": "United States, Australia",
    "imdbVotes": "464,921",
    "imdbRating": "6.8",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.178Z",
    "updatedAt": "2022-09-23T18:38:29.178Z",
    "deletedAt": null
  },
  {
    "id": 79,
    "name": "Avengers: Infinity War",
    "year": "2018",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "27 Apr 2018",
    "runtime": "149 min",
    "director": "Anthony Russo, Joe Russo",
    "actors": "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo",
    "language": "English",
    "plot": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
    "country": "United States",
    "imdbVotes": "1,049,132",
    "imdbRating": "8.4",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.285Z",
    "updatedAt": "2022-09-23T18:38:29.285Z",
    "deletedAt": null
  },
  {
    "id": 18,
    "name": "Godse",
    "year": "2022",
    "genre": "Action, Thriller",
    "poster": "https://m.media-amazon.com/images/M/MV5BZDdkNzkyYjgtMGFhMy00ZGVhLWFmYjAtZjAxOWUxZmYxM2IwXkEyXkFqcGdeQXVyMTI1NDEyNTM5._V1_SX300.jpg",
    "rated": "N/A",
    "released": "17 Jun 2022",
    "runtime": "145 min",
    "director": "Gopi Ganesh",
    "actors": "Iftekhar Mahmud, Satyadev Kancharana, Aishwarya Lekshmi",
    "language": "Telugu",
    "plot": "A reunion with friends changes the way Godse perceives the system. He begins to unravel the system's hidden agenda that robs off the careers and lives of students. What follows is a fight between Godse and the government for justice.",
    "country": "India",
    "imdbVotes": "834",
    "imdbRating": "5.6",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.661Z",
    "updatedAt": "2022-09-23T18:38:27.661Z",
    "deletedAt": null
  },
  {
    "id": 24,
    "name": "Samaritan",
    "year": "2022",
    "genre": "Action, Drama, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BY2M2MjMxNjUtZWU2MS00NTIwLWE0ZDEtOTY3NzY5NGZmY2RmXkEyXkFqcGdeQXVyODk2NDQ3MTA@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "26 Aug 2022",
    "runtime": "2 min",
    "director": "Julius Avery",
    "actors": "Sylvester Stallone, Javon 'Wanna' Walton, Pilou Asbæk",
    "language": "English",
    "plot": "A young boy learns that a superhero who was thought to have gone missing after an epic battle twenty years ago may in fact still be around.",
    "country": "United States",
    "imdbVotes": "28,807",
    "imdbRating": "5.8",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.764Z",
    "updatedAt": "2022-09-23T18:38:27.764Z",
    "deletedAt": null
  },
  {
    "id": 38,
    "name": "Thor",
    "year": "2011",
    "genre": "Action, Adventure, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BOGE4NzU1YTAtNzA3Mi00ZTA2LTg2YmYtMDJmMThiMjlkYjg2XkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "06 May 2011",
    "runtime": "115 min",
    "director": "Kenneth Branagh",
    "actors": "Chris Hemsworth, Anthony Hopkins, Natalie Portman",
    "language": "English",
    "plot": "The powerful but arrogant god Thor is cast out of Asgard to live amongst humans in Midgard (Earth), where he soon becomes one of their finest defenders.",
    "country": "United States",
    "imdbVotes": "838,112",
    "imdbRating": "7.0",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.957Z",
    "updatedAt": "2022-09-23T18:38:27.957Z",
    "deletedAt": null
  },
  {
    "id": 42,
    "name": "Tarzan 2: The Legend Begins",
    "year": "2005",
    "genre": "Animation, Adventure, Comedy, Family",
    "poster": "https://m.media-amazon.com/images/M/MV5BODUwZWRkMzAtYzFhMS00MGU5LWJhNDQtNzI2NGQ1NDA3NTBiXkEyXkFqcGdeQXVyODc5NjY4MzU@._V1_SX300.jpg",
    "rated": "G",
    "released": "13 Jun 2005",
    "runtime": "72 min",
    "director": "Brian Smith",
    "actors": "Harrison Chad, George Carlin, Brad Garrett, Ron Perlman",
    "language": "English",
    "plot": "The tale of Tarzan's misadventures as a boy as he searches for his true identity and the meaning of family.",
    "country": "USA",
    "imdbVotes": "10,138",
    "imdbRating": "5.6",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.269Z",
    "updatedAt": "2022-09-23T18:38:28.269Z",
    "deletedAt": null
  },
  {
    "id": 46,
    "name": "Thor: Ragnarok",
    "year": "2017",
    "genre": "Action, Adventure, Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjMyNDkzMzI1OF5BMl5BanBnXkFtZTgwODcxODg5MjI@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "03 Nov 2017",
    "runtime": "130 min",
    "director": "Taika Waititi",
    "actors": "Chris Hemsworth, Tom Hiddleston, Cate Blanchett",
    "language": "English",
    "plot": "Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela.",
    "country": "United States, Australia",
    "imdbVotes": "732,600",
    "imdbRating": "7.9",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.358Z",
    "updatedAt": "2022-09-23T18:38:28.358Z",
    "deletedAt": null
  },
  {
    "id": 55,
    "name": "Miami Vice",
    "year": "2006",
    "genre": "Action, Adventure, Crime",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTM4MDQ5MTkxMV5BMl5BanBnXkFtZTcwMTU4MzUzMQ@@._V1_SX300.jpg",
    "rated": "R",
    "released": "28 Jul 2006",
    "runtime": "132 min",
    "director": "Michael Mann",
    "actors": "Colin Farrell, Jamie Foxx, Gong Li",
    "language": "English, Spanish",
    "plot": "Based on the 1980s TV action/drama, this update focuses on vice detectives Crockett and Tubbs as their respective personal and professional lives become dangerously intertwined.",
    "country": "Germany, United States, Uruguay, Paraguay",
    "imdbVotes": "117,532",
    "imdbRating": "6.0",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.679Z",
    "updatedAt": "2022-09-23T18:38:28.679Z",
    "deletedAt": null
  },
  {
    "id": 62,
    "name": "Harry Potter and the Chamber of Secrets",
    "year": "2002",
    "genre": "Adventure, Family, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjE0YjUzNDUtMjc5OS00MTU3LTgxMmUtODhkOThkMzdjNWI4XkEyXkFqcGdeQXVyMTA3MzQ4MTc0._V1_SX300.jpg",
    "rated": "PG",
    "released": "15 Nov 2002",
    "runtime": "161 min",
    "director": "Chris Columbus",
    "actors": "Daniel Radcliffe, Rupert Grint, Emma Watson",
    "language": "English, Latin",
    "plot": "An ancient prophecy seems to be coming true when a mysterious presence begins stalking the corridors of a school of magic and leaving its victims paralyzed.",
    "country": "United Kingdom, United States",
    "imdbVotes": "624,688",
    "imdbRating": "7.4",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.859Z",
    "updatedAt": "2022-09-23T18:38:28.859Z",
    "deletedAt": null
  },
  {
    "id": 73,
    "name": "Fast & Furious 8",
    "year": "2014",
    "genre": "Short, Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMWVmY2MxMDAtMGIzNC00NzY0LWI1NjgtMmYxNTRhYjIxNjFkL2ltYWdlXkEyXkFqcGdeQXVyMjA5MzI3MjI@._V1_SX300.jpg",
    "rated": "N/A",
    "released": "09 Aug 2014",
    "runtime": "N/A",
    "director": "Andrew Stengele",
    "actors": "Kofi Bazzell-Smith, Jatone Smith, Chase Todd",
    "language": "English",
    "plot": "The taco stand is a cover every 3rd customer is buying a drug that genetically enhances the mind and body, but only for a short time. Then it targets the brain and starts to distort what one sees and begins to play tricks on what ...",
    "country": "United States",
    "imdbVotes": "47",
    "imdbRating": "4.5",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.166Z",
    "updatedAt": "2022-09-23T18:38:29.166Z",
    "deletedAt": null
  },
  {
    "id": 78,
    "name": "Avatar",
    "year": "2009",
    "genre": "Action, Adventure, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BNjA3NGExZDktNDlhZC00NjYyLTgwNmUtZWUzMDYwMTZjZWUyXkEyXkFqcGdeQXVyMTU1MDM3NDk0._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "18 Dec 2009",
    "runtime": "162 min",
    "director": "James Cameron",
    "actors": "Sam Worthington, Zoe Saldana, Sigourney Weaver",
    "language": "English, Spanish",
    "plot": "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    "country": "United States",
    "imdbVotes": "1,217,941",
    "imdbRating": "7.8",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.281Z",
    "updatedAt": "2022-09-23T18:38:29.281Z",
    "deletedAt": null
  },
  {
    "id": 82,
    "name": "The Dark Knight",
    "year": "2008",
    "genre": "Action, Crime, Drama",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "18 Jul 2008",
    "runtime": "152 min",
    "director": "Christopher Nolan",
    "actors": "Christian Bale, Heath Ledger, Aaron Eckhart",
    "language": "English, Mandarin",
    "plot": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    "country": "United States, United Kingdom",
    "imdbVotes": "2,603,842",
    "imdbRating": "9.0",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.561Z",
    "updatedAt": "2022-09-23T18:38:29.561Z",
    "deletedAt": null
  },
  {
    "id": 86,
    "name": "Harry Potter and the Order of the Phoenix",
    "year": "2007",
    "genre": "Action, Adventure, Family",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTM0NTczMTUzOV5BMl5BanBnXkFtZTYwMzIxNTg3._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "11 Jul 2007",
    "runtime": "31S min",
    "director": "David Yates",
    "actors": "Daniel Radcliffe, Emma Watson, Rupert Grint",
    "language": "English, Latin",
    "plot": "With their warning about Lord Voldemort's return scoffed at, Harry and Dumbledore are targeted by the Wizard authorities as an authoritarian bureaucrat slowly seizes power at Hogwarts.",
    "country": "United Kingdom, United States",
    "imdbVotes": "573,267",
    "imdbRating": "7.5",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.578Z",
    "updatedAt": "2022-09-23T18:38:29.578Z",
    "deletedAt": null
  },
  {
    "id": 90,
    "name": "Avengers: Endgame",
    "year": "2019",
    "genre": "Action, Adventure, Drama",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "26 Apr 2019",
    "runtime": "181 min",
    "director": "Anthony Russo, Joe Russo",
    "actors": "Robert Downey Jr., Chris Evans, Mark Ruffalo",
    "language": "English, Japanese, Xhosa, German",
    "plot": "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    "country": "United States",
    "imdbVotes": "1,093,492",
    "imdbRating": "8.4",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.765Z",
    "updatedAt": "2022-09-23T18:38:29.765Z",
    "deletedAt": null
  },
  {
    "id": 19,
    "name": "The Gray Man",
    "year": "2022",
    "genre": "Action, Thriller",
    "poster": "https://m.media-amazon.com/images/M/MV5BOWY4MmFiY2QtMzE1YS00NTg1LWIwOTQtYTI4ZGUzNWIxNTVmXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "22 Jul 2022",
    "runtime": "122 min",
    "director": "Anthony Russo, Joe Russo",
    "actors": "Ryan Gosling, Chris Evans, Ana de Armas",
    "language": "English",
    "plot": "When the CIA's most skilled operative-whose true identity is known to none-accidentally uncovers dark agency secrets, a psychopathic former colleague puts a bounty on his head, setting off a global manhunt by international assassins.",
    "country": "United States, Czech Republic",
    "imdbVotes": "167,193",
    "imdbRating": "6.5",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.568Z",
    "updatedAt": "2022-09-23T18:38:27.568Z",
    "deletedAt": null
  },
  {
    "id": 26,
    "name": "The Avengers",
    "year": "2012",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "04 May 2012",
    "runtime": "143 min",
    "director": "Joss Whedon",
    "actors": "Robert Downey Jr., Chris Evans, Scarlett Johansson",
    "language": "English, Russian, Hindi",
    "plot": "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
    "country": "United States",
    "imdbVotes": "1,373,524",
    "imdbRating": "8.0",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.861Z",
    "updatedAt": "2022-09-23T18:38:27.861Z",
    "deletedAt": null
  },
  {
    "id": 29,
    "name": "Interceptor",
    "year": "2022",
    "genre": "Action, Adventure, Drama",
    "poster": "https://m.media-amazon.com/images/M/MV5BZGNjYjQ3NjgtZWM0NS00MTY5LTlkZWMtODZlNzhkNTU3MzZiXkEyXkFqcGdeQXVyMjM2OTI3Mzk@._V1_SX300.jpg",
    "rated": "TV-MA",
    "released": "03 Jun 2022",
    "runtime": "1 min",
    "director": "Matthew Reilly",
    "actors": "Elsa Pataky, Luke Bracey, Aaron Glenane",
    "language": "English",
    "plot": "One Army captain must use her years of tactical training and military expertise when a simultaneous coordinated attack threatens the remote missile interceptor station she is in command of.",
    "country": "Australia, United States",
    "imdbVotes": "21,817",
    "imdbRating": "4.5",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.866Z",
    "updatedAt": "2022-09-23T18:38:27.866Z",
    "deletedAt": null
  },
  {
    "id": 33,
    "name": "The Matrix Revolutions",
    "year": "2003",
    "genre": "Action, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BNzNlZTZjMDctZjYwNi00NzljLWIwN2QtZWZmYmJiYzQ0MTk2XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
    "rated": "R",
    "released": "05 Nov 2003",
    "runtime": "2 min",
    "director": "Lana Wachowski, Lilly Wachowski",
    "actors": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
    "language": "English, French",
    "plot": "The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.",
    "country": "United States",
    "imdbVotes": "509,623",
    "imdbRating": "6.7",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.056Z",
    "updatedAt": "2022-09-23T18:38:28.056Z",
    "deletedAt": null
  },
  {
    "id": 36,
    "name": "Coco",
    "year": "2017",
    "genre": "Animation, Adventure, Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_SX300.jpg",
    "rated": "PG",
    "released": "22 Nov 2017",
    "runtime": "105 min",
    "director": "Lee Unkrich, Adrian Molina",
    "actors": "Anthony Gonzalez, Gael García Bernal, Benjamin Bratt",
    "language": "English, Spanish",
    "plot": "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
    "country": "United States",
    "imdbVotes": "492,378",
    "imdbRating": "8.4",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.259Z",
    "updatedAt": "2022-09-23T18:38:28.259Z",
    "deletedAt": null
  },
  {
    "id": 48,
    "name": "Venom",
    "year": "2018",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BNTFkZjdjN2QtOGE5MS00ZTgzLTgxZjAtYzkyZWQ5MjEzYmZjXkEyXkFqcGdeQXVyMTM0NTUzNDIy._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "05 Oct 2018",
    "runtime": "112 min",
    "director": "Ruben Fleischer",
    "actors": "Tom Hardy, Michelle Williams, Riz Ahmed",
    "language": "English, Mandarin, Malay",
    "plot": "A failed reporter is bonded to an alien entity, one of many symbiotes who have invaded Earth. But the being takes a liking to Earth and decides to protect it.",
    "country": "United States, China",
    "imdbVotes": "476,134",
    "imdbRating": "6.6",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.367Z",
    "updatedAt": "2022-09-23T18:38:28.367Z",
    "deletedAt": null
  },
  {
    "id": 50,
    "name": "La querida del Centauro",
    "year": "2016–2017",
    "genre": "Drama, Thriller",
    "poster": "https://m.media-amazon.com/images/M/MV5BNjNiYWQ2NjQtNWU1Yi00YWMxLTg0MzYtYjBhMjFmYjM4MGUyXkEyXkFqcGdeQXVyNzQ4MTE2ODk@._V1_SX300.jpg",
    "rated": "TV-14",
    "released": "12 Jan 2016",
    "runtime": "60 min",
    "director": "N/A",
    "actors": "Humberto Zurita, Michel Brown, Wayne LeGette",
    "language": "Spanish",
    "plot": "Yolanda Acosta is an attractive and intelligent woman capable of breaking the law just to protect her beloved daughter Cristina, but destiny makes her the lover of Benedicto Suárez alias El Centauro, one of the most important drug...",
    "country": "United States, Mexico, Colombia",
    "imdbVotes": "109",
    "imdbRating": "8.2",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.611Z",
    "updatedAt": "2022-09-23T18:38:28.611Z",
    "deletedAt": null
  },
  {
    "id": 53,
    "name": "Bohemian Rhapsody",
    "year": "2018",
    "genre": "Biography, Drama, Music",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTA2NDc3Njg5NDVeQTJeQWpwZ15BbWU4MDc1NDcxNTUz._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "02 Nov 2018",
    "runtime": "134 min",
    "director": "Bryan Singer",
    "actors": "Rami Malek, Lucy Boynton, Gwilym Lee",
    "language": "English, British Sign ",
    "plot": "The story of the legendary British rock band Queen and lead singer Freddie Mercury, leading up to their famous performance at Live Aid (1985).",
    "country": "United Kingdom, United States",
    "imdbVotes": "531,794",
    "imdbRating": "7.9",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.675Z",
    "updatedAt": "2022-09-23T18:38:28.675Z",
    "deletedAt": null
  },
  {
    "id": 57,
    "name": "Edge of Darkness",
    "year": "2010",
    "genre": "Action, Drama, Thriller",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTczMDk5MTg5Ml5BMl5BanBnXkFtZTcwOTYyMjE5Mg@@._V1_SX300.jpg",
    "rated": "R",
    "released": "29 Jan 2010",
    "runtime": "117 min",
    "director": "Martin Campbell",
    "actors": "Mel Gibson, Ray Winstone, Danny Huston",
    "language": "English, Latin, French",
    "plot": "As homicide detective Thomas Craven investigates the murder of his activist daughter, he uncovers a corporate cover-up and government conspiracy that attracts an agent tasked with cleaning up the evidence.",
    "country": "United Kingdom, United States",
    "imdbVotes": "94,862",
    "imdbRating": "6.6",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.764Z",
    "updatedAt": "2022-09-23T18:38:28.764Z",
    "deletedAt": null
  },
  {
    "id": 61,
    "name": "Joker",
    "year": "2019",
    "genre": "Crime, Drama, Thriller",
    "poster": "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "rated": "R",
    "released": "04 Oct 2019",
    "runtime": "122 min",
    "director": "Todd Phillips",
    "actors": "Joaquin Phoenix, Robert De Niro, Zazie Beetz",
    "language": "English",
    "plot": "A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain.",
    "country": "United States, Canada",
    "imdbVotes": "1,241,626",
    "imdbRating": "8.4",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.866Z",
    "updatedAt": "2022-09-23T18:38:28.866Z",
    "deletedAt": null
  },
  {
    "id": 66,
    "name": "Iron Man 3",
    "year": "2013",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjE5MzcyNjk1M15BMl5BanBnXkFtZTcwMjQ4MjcxOQ@@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "03 May 2013",
    "runtime": "130 min",
    "director": "Shane Black",
    "actors": "Robert Downey Jr., Guy Pearce, Gwyneth Paltrow",
    "language": "English",
    "plot": "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
    "country": "United States",
    "imdbVotes": "838,947",
    "imdbRating": "7.1",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.974Z",
    "updatedAt": "2022-09-23T18:38:28.974Z",
    "deletedAt": null
  },
  {
    "id": 70,
    "name": "The Avengers",
    "year": "2012",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "04 May 2012",
    "runtime": "143 min",
    "director": "Joss Whedon",
    "actors": "Robert Downey Jr., Chris Evans, Scarlett Johansson",
    "language": "English, Russian, Hindi",
    "plot": "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
    "country": "United States",
    "imdbVotes": "1,373,524",
    "imdbRating": "8.0",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.076Z",
    "updatedAt": "2022-09-23T18:38:29.076Z",
    "deletedAt": null
  },
  {
    "id": 75,
    "name": "Captain America: Civil War",
    "year": "2016",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjQ0MTgyNjAxMV5BMl5BanBnXkFtZTgwNjUzMDkyODE@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "06 May 2016",
    "runtime": "147 min",
    "director": "Anthony Russo, Joe Russo",
    "actors": "Chris Evans, Robert Downey Jr., Scarlett Johansson",
    "language": "English, German, Xhosa, Russian, Romanian, Hindi",
    "plot": "Political involvement in the Avengers' affairs causes a rift between Captain America and Iron Man.",
    "country": "United States",
    "imdbVotes": "772,434",
    "imdbRating": "7.8",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.258Z",
    "updatedAt": "2022-09-23T18:38:29.258Z",
    "deletedAt": null
  },
  {
    "id": 81,
    "name": "Doctor Strange in the Multiverse of Madness",
    "year": "2022",
    "genre": "Action, Adventure, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "06 May 2022",
    "runtime": "126 min",
    "director": "Sam Raimi",
    "actors": "Benedict Cumberbatch, Elizabeth Olsen, Chiwetel Ejiofor",
    "language": "English, Spanish, Chinese",
    "plot": "Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the mul...",
    "country": "United States",
    "imdbVotes": "380,319",
    "imdbRating": "7.0",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.559Z",
    "updatedAt": "2022-09-23T18:38:29.559Z",
    "deletedAt": null
  },
  {
    "id": 76,
    "name": "Toy Story 4",
    "year": "2019",
    "genre": "Animation, Adventure, Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTYzMDM4NzkxOV5BMl5BanBnXkFtZTgwNzM1Mzg2NzM@._V1_SX300.jpg",
    "rated": "G",
    "released": "21 Jun 2019",
    "runtime": "100 min",
    "director": "Josh Cooley",
    "actors": "Tom Hanks, Tim Allen, Annie Potts",
    "language": "English",
    "plot": "When a new toy called \"Forky\" joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy.",
    "country": "United States",
    "imdbVotes": "245,952",
    "imdbRating": "7.7",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.176Z",
    "updatedAt": "2022-09-23T18:38:29.176Z",
    "deletedAt": null
  },
  {
    "id": 80,
    "name": "Beauty and the Beast",
    "year": "1991",
    "genre": "Animation, Family, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMzE5MDM1NDktY2I0OC00YWI5LTk2NzUtYjczNDczOWQxYjM0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    "rated": "G",
    "released": "22 Nov 1991",
    "runtime": "84 min",
    "director": "Gary Trousdale, Kirk Wise",
    "actors": "Paige O'Hara, Robby Benson, Jesse Corti",
    "language": "English, French",
    "plot": "A prince cursed to spend his days as a hideous monster sets out to regain his humanity by earning a young woman's love.",
    "country": "United States",
    "imdbVotes": "450,983",
    "imdbRating": "8.0",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.471Z",
    "updatedAt": "2022-09-23T18:38:29.471Z",
    "deletedAt": null
  },
  {
    "id": 85,
    "name": "Alice in Wonderland",
    "year": "2010",
    "genre": "Adventure, Family, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTMwNjAxMTc0Nl5BMl5BanBnXkFtZTcwODc3ODk5Mg@@._V1_SX300.jpg",
    "rated": "PG",
    "released": "05 Mar 2010",
    "runtime": "32S min",
    "director": "Tim Burton",
    "actors": "Mia Wasikowska, Johnny Depp, Helena Bonham Carter",
    "language": "English",
    "plot": "Nineteen-year-old Alice returns to the magical world from her childhood adventure, where she reunites with her old friends and learns of her true destiny: to end the Red Queen's reign of terror.",
    "country": "United States",
    "imdbVotes": "412,115",
    "imdbRating": "6.4",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.574Z",
    "updatedAt": "2022-09-23T18:38:29.574Z",
    "deletedAt": null
  },
  {
    "id": 89,
    "name": "Jurassic World",
    "year": "2015",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BNzQ3OTY4NjAtNzM5OS00N2ZhLWJlOWUtYzYwZjNmOWRiMzcyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "12 Jun 2015",
    "runtime": "124 min",
    "director": "Colin Trevorrow",
    "actors": "Chris Pratt, Bryce Dallas Howard, Ty Simpkins",
    "language": "English",
    "plot": "A new theme park, built on the original site of Jurassic Park, creates a genetically modified hybrid dinosaur, the Indominus Rex, which escapes containment and goes on a killing spree.",
    "country": "United States",
    "imdbVotes": "637,459",
    "imdbRating": "6.9",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.679Z",
    "updatedAt": "2022-09-23T18:38:29.679Z",
    "deletedAt": null
  },
  {
    "id": 92,
    "name": "The Lion King",
    "year": "1994",
    "genre": "Animation, Adventure, Drama",
    "poster": "https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_SX300.jpg",
    "rated": "G",
    "released": "24 Jun 1994",
    "runtime": "88 min",
    "director": "Roger Allers, Rob Minkoff",
    "actors": "Matthew Broderick, Jeremy Irons, James Earl Jones",
    "language": "English, Swahili, Xhosa, Zulu",
    "plot": "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
    "country": "United States",
    "imdbVotes": "1,044,433",
    "imdbRating": "8.5",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.770Z",
    "updatedAt": "2022-09-23T18:38:29.770Z",
    "deletedAt": null
  },
  {
    "id": 83,
    "name": "Star Wars: Episode VIII - The Last Jedi",
    "year": "2017",
    "genre": "Action, Adventure, Fantasy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjQ1MzcxNjg4N15BMl5BanBnXkFtZTgwNzgwMjY4MzI@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "15 Dec 2017",
    "runtime": "152 min",
    "director": "Rian Johnson",
    "actors": "Daisy Ridley, John Boyega, Mark Hamill",
    "language": "English",
    "plot": "The Star Wars saga continues as new heroes and galactic legends go on an epic adventure, unlocking mysteries of the Force and shocking revelations of the past.",
    "country": "United States",
    "imdbVotes": "625,040",
    "imdbRating": "6.9",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.567Z",
    "updatedAt": "2022-09-23T18:38:29.567Z",
    "deletedAt": null
  },
  {
    "id": 91,
    "name": "Toy Story 3",
    "year": "2010",
    "genre": "Animation, Adventure, Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
    "rated": "G",
    "released": "18 Jun 2010",
    "runtime": "103 min",
    "director": "Lee Unkrich",
    "actors": "Tom Hanks, Tim Allen, Joan Cusack",
    "language": "English, Spanish",
    "plot": "The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it's up to Woody to convince the other toys that they weren't abandoned and to return home.",
    "country": "United States",
    "imdbVotes": "826,433",
    "imdbRating": "8.3",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.665Z",
    "updatedAt": "2022-09-23T18:38:29.665Z",
    "deletedAt": null
  },
  {
    "id": 87,
    "name": "Avengers: Age of Ultron",
    "year": "2015",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTM4OGJmNWMtOTM4Ni00NTE3LTg3MDItZmQxYjc4N2JhNmUxXkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "01 May 2015",
    "runtime": "141 min",
    "director": "Joss Whedon",
    "actors": "Robert Downey Jr., Chris Evans, Mark Ruffalo",
    "language": "English, Korean",
    "plot": "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan.",
    "country": "United States",
    "imdbVotes": "852,577",
    "imdbRating": "7.3",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.581Z",
    "updatedAt": "2022-09-23T18:38:29.581Z",
    "deletedAt": null
  },
  {
    "id": 93,
    "name": "Spider-Man: Far from Home",
    "year": "2019",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BMGZlNTY1ZWUtYTMzNC00ZjUyLWE0MjQtMTMxN2E3ODYxMWVmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "02 Jul 2019",
    "runtime": "129 min",
    "director": "Jon Watts",
    "actors": "Tom Holland, Samuel L. Jackson, Jake Gyllenhaal",
    "language": "English, Italian, Czech",
    "plot": "Following the events of Avengers: Endgame (2019), Spider-Man must step up to take on new threats in a world that has changed forever.",
    "country": "United States",
    "imdbVotes": "478,702",
    "imdbRating": "7.4",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.766Z",
    "updatedAt": "2022-09-23T18:38:29.766Z",
    "deletedAt": null
  },
  {
    "id": 20,
    "name": "Major League",
    "year": "1989",
    "genre": "Comedy, Sport",
    "poster": "https://m.media-amazon.com/images/M/MV5BNzM5MWViNTMtMDQ5Ni00M2M0LTg1OTktY2I3YTJkODVkNTBkXkEyXkFqcGdeQXVyNTI4MjkwNjA@._V1_SX300.jpg",
    "rated": "R",
    "released": "07 Apr 1989",
    "runtime": "107 min",
    "director": "David S. Ward",
    "actors": "Tom Berenger, Charlie Sheen, Corbin Bernsen",
    "language": "English, Spanish, Japanese",
    "plot": "The new owner of the Cleveland Indians puts together a purposely horrible team so they'll lose and she can move the team. But when the plot is uncovered, they start winning just to spite her.",
    "country": "United States",
    "imdbVotes": "69,531",
    "imdbRating": "7.2",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.565Z",
    "updatedAt": "2022-09-23T18:38:27.565Z",
    "deletedAt": null
  },
  {
    "id": 22,
    "name": "F.I.R NO. 339/07/06",
    "year": "2021",
    "genre": "Crime, Drama, Thriller",
    "poster": "https://m.media-amazon.com/images/M/MV5BZTA3MTAwYTEtYzFlNS00YWJkLWE2NjEtZGE3YmQwYjAwYjAxXkEyXkFqcGdeQXVyNjk3MjI4NDg@._V1_SX300.jpg",
    "rated": "N/A",
    "released": "10 Oct 2021",
    "runtime": "2 min",
    "director": "Joydeep Mukherjee",
    "actors": "Ritabhari Chakraborty, Ankush Hazra, Santilal Mukherjee",
    "language": "Bengali",
    "plot": "The plot revolves around a police officer. He fights for justice and decides to go to any extent. Things take a turn as it changes everything forever. Will he be able to punish the culprits forever?",
    "country": "India",
    "imdbVotes": "274",
    "imdbRating": "6.6",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.759Z",
    "updatedAt": "2022-09-23T18:38:27.759Z",
    "deletedAt": null
  },
  {
    "id": 27,
    "name": "Indiana Jones and the Kingdom of the Crystal Skull",
    "year": "2008",
    "genre": "Action, Adventure",
    "poster": "https://m.media-amazon.com/images/M/MV5BZmY5ZTk3ZDMtZjA1MS00NzU4LTk5ZDItYmNhOTkxMGYxMjRlXkEyXkFqcGdeQXVyMjM4MzQ4OTQ@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "22 May 2008",
    "runtime": "122 min",
    "director": "Steven Spielberg",
    "actors": "Harrison Ford, Cate Blanchett, Shia LaBeouf",
    "language": "English, German, Russian",
    "plot": "In 1957, archaeologist and adventurer Dr. Henry \"Indiana\" Jones, Jr. is called back into action and becomes entangled in a Soviet plot to uncover the secret behind mysterious artifacts known as the Crystal Skulls.",
    "country": "United States",
    "imdbVotes": "451,665",
    "imdbRating": "6.1",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.856Z",
    "updatedAt": "2022-09-23T18:38:27.856Z",
    "deletedAt": null
  },
  {
    "id": 39,
    "name": "John Carter",
    "year": "2012",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BMDEwZmIzNjYtNjUwNS00MzgzLWJiOGYtZWMxZGQ5NDcxZjUwXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "09 Mar 2012",
    "runtime": "132 min",
    "director": "Andrew Stanton",
    "actors": "Taylor Kitsch, Lynn Collins, Willem Dafoe",
    "language": "English",
    "plot": "Transported to Barsoom, a Civil War vet discovers a barren planet seemingly inhabited by 12-foot tall barbarians. Finding himself prisoner of these creatures, he escapes, only to encounter Woola and a princess in desperate need of...",
    "country": "United States",
    "imdbVotes": "271,967",
    "imdbRating": "6.6",
    "status": true,
    "createdAt": "2022-09-23T18:38:27.959Z",
    "updatedAt": "2022-09-23T18:38:27.959Z",
    "deletedAt": null
  },
  {
    "id": 47,
    "name": "Harry Potter and the Half-Blood Prince",
    "year": "2009",
    "genre": "Action, Adventure, Family",
    "poster": "https://m.media-amazon.com/images/M/MV5BNzU3NDg4NTAyNV5BMl5BanBnXkFtZTcwOTg2ODg1Mg@@._V1_SX300.jpg",
    "rated": "PG",
    "released": "15 Jul 2009",
    "runtime": "2 min",
    "director": "David Yates",
    "actors": "Daniel Radcliffe, Emma Watson, Rupert Grint",
    "language": "English, Latin",
    "plot": "As Harry Potter begins his sixth year at Hogwarts, he discovers an old book marked as \"the property of the Half-Blood Prince\" and begins to learn more about Lord Voldemort's dark past.",
    "country": "United Kingdom, United States",
    "imdbVotes": "537,045",
    "imdbRating": "7.6",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.597Z",
    "updatedAt": "2022-09-23T18:38:28.597Z",
    "deletedAt": null
  },
  {
    "id": 56,
    "name": "Finding Nemo",
    "year": "2003",
    "genre": "Animation, Adventure, Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BZTAzNWZlNmUtZDEzYi00ZjA5LWIwYjEtZGM1NWE1MjE4YWRhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    "rated": "G",
    "released": "30 May 2003",
    "runtime": "100 min",
    "director": "Andrew Stanton, Lee Unkrich",
    "actors": "Albert Brooks, Ellen DeGeneres, Alexander Gould",
    "language": "English",
    "plot": "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
    "country": "United States",
    "imdbVotes": "1,031,480",
    "imdbRating": "8.2",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.684Z",
    "updatedAt": "2022-09-23T18:38:28.684Z",
    "deletedAt": null
  },
  {
    "id": 58,
    "name": "The Secret Life of Pets",
    "year": "2016",
    "genre": "Animation, Adventure, Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjIzMzA1OTkzNV5BMl5BanBnXkFtZTgwODE3MjM4NzE@._V1_SX300.jpg",
    "rated": "PG",
    "released": "08 Jul 2016",
    "runtime": "87 min",
    "director": "Chris Renaud",
    "actors": "Louis C.K., Eric Stonestreet, Kevin Hart",
    "language": "English",
    "plot": "The quiet life of a terrier named Max is upended when his owner takes in Duke, a stray whom Max instantly dislikes.",
    "country": "United States, Japan",
    "imdbVotes": "201,122",
    "imdbRating": "6.5",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.791Z",
    "updatedAt": "2022-09-23T18:38:28.791Z",
    "deletedAt": null
  },
  {
    "id": 65,
    "name": "Jurassic World: Fallen Kingdom",
    "year": "2018",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BNzIxMjYwNDEwN15BMl5BanBnXkFtZTgwMzk5MDI3NTM@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "22 Jun 2018",
    "runtime": "128 min",
    "director": "J.A. Bayona",
    "actors": "Chris Pratt, Bryce Dallas Howard, Rafe Spall",
    "language": "English, Russian",
    "plot": "When the island's dormant volcano begins roaring to life, Owen and Claire mount a campaign to rescue the remaining dinosaurs from this extinction-level event.",
    "country": "United States, China",
    "imdbVotes": "312,740",
    "imdbRating": "6.1",
    "status": true,
    "createdAt": "2022-09-23T18:38:28.882Z",
    "updatedAt": "2022-09-23T18:38:28.882Z",
    "deletedAt": null
  },
  {
    "id": 67,
    "name": "Jumanji: Welcome to the Jungle",
    "year": "2017",
    "genre": "Action, Adventure, Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BODQ0NDhjYWItYTMxZi00NTk2LWIzNDEtOWZiYWYxZjc2MTgxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "20 Dec 2017",
    "runtime": "119 min",
    "director": "Jake Kasdan",
    "actors": "Dwayne Johnson, Karen Gillan, Kevin Hart",
    "language": "English",
    "plot": "Four teenagers are sucked into a magical video game, and the only way they can escape is to work together to finish the game.",
    "country": "United States",
    "imdbVotes": "373,574",
    "imdbRating": "6.9",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.069Z",
    "updatedAt": "2022-09-23T18:38:29.069Z",
    "deletedAt": null
  },
  {
    "id": 72,
    "name": "Incredibles 2",
    "year": "2018",
    "genre": "Animation, Action, Adventure",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTEzNzY0OTg0NTdeQTJeQWpwZ15BbWU4MDU3OTg3MjUz._V1_SX300.jpg",
    "rated": "PG",
    "released": "15 Jun 2018",
    "runtime": "118 min",
    "director": "Brad Bird",
    "actors": "Craig T. Nelson, Holly Hunter, Sarah Vowell",
    "language": "English",
    "plot": "The Incredibles family takes on a new mission which involves a change in family roles: Bob Parr (Mr. Incredible) must manage the house while his wife Helen (Elastigirl) goes out to save the world.",
    "country": "United States",
    "imdbVotes": "292,459",
    "imdbRating": "7.6",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.171Z",
    "updatedAt": "2022-09-23T18:38:29.171Z",
    "deletedAt": null
  },
  {
    "id": 77,
    "name": "Harry Potter and the Deathly Hallows: Part 2",
    "year": "2011",
    "genre": "Adventure, Fantasy, Mystery",
    "poster": "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "15 Jul 2011",
    "runtime": "130 min",
    "director": "David Yates",
    "actors": "Daniel Radcliffe, Emma Watson, Rupert Grint",
    "language": "English, Latin",
    "plot": "Harry, Ron, and Hermione search for Voldemort's remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.",
    "country": "United Kingdom, United States",
    "imdbVotes": "861,205",
    "imdbRating": "8.1",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.278Z",
    "updatedAt": "2022-09-23T18:38:29.278Z",
    "deletedAt": null
  },
  {
    "id": 84,
    "name": "Aladdin",
    "year": "1992",
    "genre": "Animation, Adventure, Comedy",
    "poster": "https://m.media-amazon.com/images/M/MV5BY2Q2NDI1MjUtM2Q5ZS00MTFlLWJiYWEtNTZmNjQ3OGJkZDgxXkEyXkFqcGdeQXVyNTI4MjkwNjA@._V1_SX300.jpg",
    "rated": "G",
    "released": "25 Nov 1992",
    "runtime": "90 min",
    "director": "Ron Clements, John Musker",
    "actors": "Scott Weinger, Robin Williams, Linda Larkin",
    "language": "English",
    "plot": "A kindhearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.",
    "country": "United States",
    "imdbVotes": "413,283",
    "imdbRating": "8.0",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.456Z",
    "updatedAt": "2022-09-23T18:38:29.456Z",
    "deletedAt": null
  },
  {
    "id": 88,
    "name": "Black Panther",
    "year": "2018",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "16 Feb 2018",
    "runtime": "134 min",
    "director": "Ryan Coogler",
    "actors": "Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o",
    "language": "English, Swahili, Nama, Xhosa, Korean",
    "plot": "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
    "country": "United States",
    "imdbVotes": "743,117",
    "imdbRating": "7.3",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.671Z",
    "updatedAt": "2022-09-23T18:38:29.671Z",
    "deletedAt": null
  },
  {
    "id": 94,
    "name": "Captain Marvel",
    "year": "2019",
    "genre": "Action, Adventure, Sci-Fi",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTE0YWFmOTMtYTU2ZS00ZTIxLWE3OTEtYTNiYzBkZjViZThiXkEyXkFqcGdeQXVyODMzMzQ4OTI@._V1_SX300.jpg",
    "rated": "PG-13",
    "released": "08 Mar 2019",
    "runtime": "123 min",
    "director": "Anna Boden, Ryan Fleck",
    "actors": "Brie Larson, Samuel L. Jackson, Ben Mendelsohn",
    "language": "English",
    "plot": "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
    "country": "United States, Australia",
    "imdbVotes": "548,794",
    "imdbRating": "6.8",
    "status": true,
    "createdAt": "2022-09-23T18:38:29.768Z",
    "updatedAt": "2022-09-23T18:38:29.768Z",
    "deletedAt": null
  }
]

let genres = [];
  data.forEach((e) => {
    genres = genres.concat(e.genre.split(","));
  });
  let setGenre = new Set(genres.map((e) => e.trim()));
  export let allgenre = [...setGenre];

  export let user = {
    id: 17,
    name: "gabotonder",
    lastname: "villasssssss",
    nickname: "gefv1891",
    picture: "https://lh3.googleusercontent.com/a-/ACNPEu_Jglj41TwwdBvDquVg3nWv5a0LZ0SK5XSaby10UQ=s96-c",
    email: "gefv1891@gmail.com",
    date: "1991-09-18",
    status: true,
    category: "user",
    createdAt: "2022-09-27T01:25:57.093Z",
    updatedAt: "2022-09-29T21:23:45.461Z",
    deletedAt: null
  }
